# introduction to opp python
### on of the popular approach to solve a programming problem by creating an objects,this is known as object oriented programming \
### 1. inheritance
### 2.encapsulation
### 3.polymorphism

## class:

### a class is blueprint of the object or logical entity

## object:
### blueprint of cxlass or instance of the class or physical entity

## methods:
### part of class and can be called with

In [6]:
def test():
    print('test() for function')
    return
test()

test() for function


In [8]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj= Demo()
obj.test()

test() for the class and method


In [11]:
class Demo1:
    def fact(self,n):
        fact = 1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
p1.fact(5)

120

In [20]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1 = p1
        self.p2 = p2
    def add(self,p1,p2):
        return p1 + p2
c1= Demo2(10,20)
print(c1.add(100,200))

300


In [21]:
class Demo2:
    def accept(self,p1,p2):
        a = p1
        b = p2
        return
    def display(self,p1,p2):
        print("p1= ",p1)
        print("p2= ",p2)   
c1 = Demo2()
c1.accept(10,20)
c1.display(10,20)



p1=  10
p2=  20


In [3]:
import numpy as np
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2][3] = 14
np.asarray(a)[3][3] = 16 
print(a)

[[ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1 16]]


In [6]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [8]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [12]:
# indexing and slicing of numpy
a1 = np.array([(1,2,3),(4,5,6,)])
print(a1)

[[1 2 3]
 [4 5 6]]


a1 = np.array([(1,2,3),(4,5,6)])
print("first row",a1[0])

a1 = np.array([(1,2,3),(4,5,6)])
print("second row",a1[1])

In [14]:
a1 = np.array([(1,2,3),(4,5,6)])
print("row and column",a1[1:2])

row and column [[4 5 6]]


a1 = np.random.normal(5,1,10)
print(a1)

##  Some Math Operation On Given Random Numbers
### min---returns the least number
### max---returns the large number 
### mean---mean
### median---median
### GD---Gaussian Distribution

In [11]:
import numpy as np
a1 = np.random.normal(5,1,10)
print(a1)
print("Min value = ",np.min(a1))
print("Max value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("Median value = ",np.median(a1))

[5.86553291 5.20619445 4.56801154 5.32970583 5.1461319  6.31729079
 5.23546741 6.62443686 5.11645238 4.32410811]
Min value =  4.324108108752421
Max value =  6.6244368570380825
Mean value =  5.373333218252728
Median value =  5.220830931642739


## pandas basics
python is one of the popular programming language for data analysis <br>
python is offering the lib called pandas used for importing and analaysing and analaysing pretty much faster and easier
 
 pandas data for 

In [16]:
import pandas as pd
dict ={"Name": ["vandu","manish","akkii","priyanth","saii","ram"],
      "EmailID":["rampudisaipriya@gmail.com","akankshareddy6430@gmail.com","priyanth@gmail.com","vustelamanishreddy@gmail.com","ramchowdhryrampudi@gmail.com","vandanaayineni@gmail.com"],
      "Moible number" : [11,22,33,44,55,66],
      "Adress":["hyd","hyd","hyd","hyd","hyd","hyd"]}
b = pd.DataFrame(dict)
print(b)

       Name                       EmailID  Moible number Adress
0     vandu     rampudisaipriya@gmail.com             11    hyd
1    manish   akankshareddy6430@gmail.com             22    hyd
2     akkii            priyanth@gmail.com             33    hyd
3  priyanth  vustelamanishreddy@gmail.com             44    hyd
4      saii  ramchowdhryrampudi@gmail.com             55    hyd
5       ram      vandanaayineni@gmail.com             66    hyd
